version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - rubygems-v1-{{ checksum "Gemfile.lock" }}
            - rubygems-v1-fallback
      - run: bundle install
      - run: bundle exec jekyll build --verbose
      # - run:
      #     name: Test
      #     command: bundle exec htmlproofer ./_site --check-html --disable-external
      - run: sudo apt-get upgrade -y && sudo apt-get install -y rsync
      - deploy:
          name: Deploy Release
          command: rsync -va --delete ./_site site@primcraft.com:/home/wwwroot/primcraft.com/web
workflows:
  version: 2
  build:
    jobs:
      - deploy